=== Project-MONAI/model-zoo/models/lung_nodule_ct_detection/eval/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "schema": {
            "description": "URL of the schema file.",
            "type": "string"
        },
        "version": {
            "description": "version number of the model package.",
            "type": "string"
        },
        "changelog": {
            "description": "dictionary relating previous version names to strings describing the version.",
            "type": "object"
        },
        "monai_version": {
            "description": "version of MONAI the model package was generated on.",
            "type": "string"
        },
        "pytorch_version": {
            "description": "version of PyTorch the model package was generated on.",
            "type": "string"
        },
        "numpy_version": {
            "description": "version of NumPy the model package was generated on.",
            "type": "string"
        },
        "optional_packages_version": {
            "description": "dictionary relating optional package names to their versions.",
            "type": "object"
        },
        "task": {
            "description": "plain-language description of what the model is meant to do.",
            "type": "string"
        },
        "description": {
            "description": "longer form plain-language description of what the model is, what it does, etc.",
            "type": "string"
        },
        "authors": {
            "description": "state author(s) of the model package.",
            "type": "string"
        },
        "copyright": {
            "description": "state copyright of the model package.",
            "type": "string"
        },
        "data_source": {
            "description": "where to download or prepare the data used in this model package.",
            "type": "string"
        },
        "data_type": {
            "description": "type of the data, like: `dicom`, `nibabel`, etc.",
            "type": "string"
        },
        "image_classes": {
            "description": "description for every class of the input image.",
            "type": "string"
        },
        "label_classes": {
            "description": "description for every class of the input label.",
            "type": "string"
        },
        "pred_classes": {
            "description": "description for every class of the output prediction.",
            "type": "string"
        },
        "eval_metrics": {
            "description": "dictionary relating evaluation metrics to the achieved scores.",
            "type": "object"
        },
        "intended_use": {
            "description": "what the model package is to be used for, ie. what task it accomplishes.",
            "type": "string"
        },
        "references": {
            "description": "list of published referenced relating to the model package.",
            "type": "array"
        },
        "network_data_format": {
            "description": "defines the format, shape, and meaning of inputs and outputs to the model.",
            "type": "object",
            "properties": {
                "inputs": {
                    "type": "object",
                    "properties": {
                        "image": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string"
                                },
                                "format": {
                                    "type": "string"
                                },
                                "num_channels": {
                                    "type": "integer"
                                },
                                "spatial_shape": {
                                    "type": "array"
                                },
                                "dtype": {
                                    "type": "string"
                                },
                                "value_range": {
                                    "type": "array",
                                    "items": {
                                        "type": "number"
                                    }
                                },
                                "is_patch_data": {
                                    "type": "boolean"
                                },
                                "channel_def": {
                                    "type": "object"
                                }
                            },
                            "required": [
                                "type",
                                "format",
                                "num_channels",
                                "spatial_shape",
                                "dtype",
                                "value_range"
                            ]
                        },
                        "label": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string"
                                },
                                "format": {
                                    "type": "string"
                                },
                                "num_channels": {
                                    "type": "integer"
                                },
                                "spatial_shape": {
                                    "type": "array"
                                },
                                "dtype": {
                                    "type": "string"
                                },
                                "value_range": {
                                    "type": "array",
                                    "items": {
                                        "type": "number"
                                    }
                                },
                                "is_patch_data": {
                                    "type": "boolean"
                                },
                                "channel_def": {
                                    "type": "object"
                                }
                            },
                            "required": [
                                "type",
                                "format",
                                "num_channels",
                                "spatial_shape",
                                "dtype",
                                "value_range"
                            ]
                        }
                    },
                    "required": [
                        "image"
                    ]
                },
                "outputs": {
                    "type": "object",
                    "properties": {
                        "pred": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string"
                                },
                                "format": {
                                    "type": "string"
                                },
                                "num_channels": {
                                    "type": "integer"
                                },
                                "spatial_shape": {
                                    "type": "array"
                                },
                                "dtype": {
                                    "type": "string"
                                },
                                "value_range": {
                                    "type": "array",
                                    "items": {
                                        "type": "number"
                                    }
                                },
                                "is_patch_data": {
                                    "type": "boolean"
                                },
                                "channel_def": {
                                    "type": "object"
                                }
                            },
                            "required": [
                                "type",
                                "format",
                                "num_channels",
                                "spatial_shape",
                                "dtype",
                                "value_range"
                            ]
                        }
                    },
                    "required": [
                        "pred"
                    ]
                }
            },
            "required": [
                "inputs",
                "outputs"
            ]
        }
    },
    "required": [
        "schema",
        "version",
        "monai_version",
        "pytorch_version",
        "numpy_version",
        "optional_packages_version",
        "task",
        "description",
        "authors",
        "copyright",
        "network_data_format"
    ]
}

=== Project-MONAI/model-zoo/models/pathology_multiple_instance_learning_classification/configs/metadata.json
{
    "schema": "https://github.com/Project-MONAI/MONAI-extra-test-data/releases/download/0.8.1/meta_schema_20220324.json",
    "version": "0.1.0",
    "changelog": {
        "0.1.0": "complete the model package"
    },
    "monai_version": "1.1.0",
    "pytorch_version": "1.13.0",
    "numpy_version": "1.22.2",
    "optional_packages_version": {
        "cucim": "22.10.0",
        "gdown": "4.5.4"
    },
    "task": " Multiple Instance Learning (MIL) classification from Whole Slide Images (WSI).",
    "description": "A pre-trained baseline model for Multiple Instance Learning (MIL) classification from Whole Slide Images (WSI) based on PANDA 2020 data",
    "authors": "MONAI team",
    "copyright": "Copyright (c) MONAI Consortium",
    "data_source": "https://www.kaggle.com/c/prostate-cancer-grade-assessment/",
    "data_type": "tiff",
    "image_classes": "3 channel RGB data, 2D TIFF WSI",
    "label_classes": "5 classes, ISUP grade",
    "pred_classes": "5 classes, ISUP grade",
    "eval_metrics": {
        "QWK": 0.9071
    },
    "intended_use": "This is an example, not to be used for diagnostic purposes",
    "references": [
        "Andriy Myronenko, Ziyue Xu, Dong Yang, Holger Roth, Daguang Xu: 'Accounting for Dependencies in Deep Learning Based Multiple Instance Learning for Whole Slide Imaging'. In MICCAI (2021). https://arxiv.org/abs/2111.01556"
    ],
    "network_data_format": {
        "inputs": {
            "image": {
                "type": "image",
                "format": "magnitude",
                "modality": "TIFF",
                "num_channels": 3,
                "spatial_shape": [
                    "256*n",
                    "256*n"
                ],
                "dtype": "uint8",
                "value_range": [],
                "is_patch_data": true,
                "channel_def": {
                    "0": "R",
                    "1": "G",
                    "2": "B"
                }
            }
        },
        "outputs": {
            "pred": {
                "type": "image",
                "format": "labels",
                "dtype": "int",
                "value_range": [
                    0,
                    5
                ],
                "num_channels": 1,
                "spatial_shape": [
                    1
                ],
                "is_patch_data": false,
                "channel_def": {
                    "0": "ISUP grade"
                }
            }
        }
    }
}
